'use strict';
module.exports = (app) => {
  const mealAppsContorller = require('../controllers/mealAppsContorller');
  app
    .route('/api/mealApps/add-link-mealApp-user/:token')
    .post(mealAppsContorller.add_link_mealApp_user);
  app
    .route('/api/mealApps/add-link-mealApp-admin')
    .post(mealAppsContorller.add_link_mealApp_admin);
  app
    .route('/api/mealApps/get-deliveroo-PDF-user/:token/:restaurantId')
    .get(mealAppsContorller.get_deliveroo_PDF_user);
  app
    .route('/api/mealApps/get-deliveroo-PDF-admin/:requesterId/:restaurantId')
    .get(mealAppsContorller.get_deliveroo_PDF_admin);
  app
    .route('/api/mealApps/get-justEat-PDF-user/:token/:restaurantId')
    .get(mealAppsContorller.get_justEat_PDF_user);
  app
    .route('/api/mealApps/get-justEat-PDF-admin/:requesterId/:restaurantId')
    .get(mealAppsContorller.get_justEat_PDF_admin);
  app
    .route('/api/mealApps/get-uberEats-PDF-user/:token/:restaurantId')
    .get(mealAppsContorller.get_uberEats_PDF_user);
  app
    .route('/api/mealApps/get-uberEats-PDF-admin/:requesterId/:restaurantId')
    .get(mealAppsContorller.get_uberEats_PDF_admin);
  app
    .route(
      '/api/mealApps/get-takeaway-qrcode-user/:token/:restaurantId/:service'
    )
    .get(mealAppsContorller.get_takeaway_qrcode_user);
  app
    .route('/api/mealApps/get-takeaway-qrcode-admin/:requesterId')
    .post(mealAppsContorller.get_takeaway_qrcode_admin);
  app
    .route('/api/mealApps/remove-meal-app-object-user/:token')
    .post(mealAppsContorller.remove_meal_app_object_user);
  app
    .route('/api/mealApps/remove-meal-app-object-admin/:requesterId')
    .post(mealAppsContorller.remove_meal_app_object_admin);
};
